# Generated by Django 3.2.5 on 2021-07-29 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_firstname', models.CharField(max_length=255)),
                ('employee_lastname', models.CharField(max_length=255)),
                ('employee_dob', models.DateField()),
                ('employee_department', models.CharField(max_length=255)),
                ('employee_unit', models.CharField(max_length=255)),
                ('employee_rate', models.IntegerField(default=0)),
                ('employee_baseSalary', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('salary_id', models.IntegerField(primary_key=True, serialize=False)),
                ('salary_amount', models.IntegerField(default=0)),
                ('amount_paid', models.IntegerField(default=0)),
                ('due_date', models.IntegerField()),
                ('date_paid', models.IntegerField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('payroll_id', models.IntegerField(primary_key=True, serialize=False)),
                ('comphourlyRate', models.IntegerField(default=0)),
                ('daysClocked', models.IntegerField(default=0)),
                ('salary', models.IntegerField(default=0)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employees')),
            ],
        ),
    ]
